In [2]:
import pandas as pd


df = pd.read_csv('dataset_teste.csv')

In [3]:
df

                                                      text  label
0        Add test for PR1996. (This is my first time ad...      1
1                [ARM] Rotated operand patterns for *xtb16      1
2        New test case for C Writer regression found in...      1
3        [Autofill Assistant] Fixed dividers that were ...      1
4                     blk-merge: fix blk_bio_segment_split      1
...                                                    ...    ...
4054338  Define classes for unary and binary FP instruc...      1
4054339  Oilpan: Call Heap::increaseCollectedWrapperCou...      1
4054340      Delete dead code and add asserts instead; NFC      1
4054341  [stdlib][swift-3-indexing-model] un-commenting...      1
4054342  [libcxx] Improve code generation for vector::c...      1

[4054343 rows x 2 columns]

In [6]:
df['label'].value_counts()

label
1    4036477
0      17866
Name: count, dtype: int64

In [7]:
# deixe o dataset com o mesmo numero de linhas de cada label
df = df.groupby('label').apply(lambda x: x.sample(df['label'].value_counts().min()).reset_index(drop=True))
df
df['label'].value_counts()

/tmp/ipykernel_90479/1610519988.py:2: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df = df.groupby('label').apply(lambda x: x.sample(df['label'].value_counts().min()).reset_index(drop=True))

label
0    17866
1    17866
Name: count, dtype: int64

In [8]:
df

                                                          text  label
label
0     0          if i could only play oneid pick 552 moonscars      0
      1      i’m surprised that he didn’t know that all bed...      0
      2      can we all agree these videos are never disapp...      0
      3      “i’m still blending because i don’t want my mo...      0
      4      i need his enthusiasm for my studies his passi...      0
...                                                        ...    ...
1     17861       Updating trunk VERSION from 3779.0 to 3780.0      1
      17862  alpha: use L1_CACHE_BYTES for cacheline size i...      1
      17863  Update page directory in Win32 project to matc...      1
      17864  Rene Liebscher: when fixing up directories wit...      1
      17865  Import wpt@cbd8c8ca929bc1aea71087be3b826cf1ee1...      1

[35732 rows x 2 columns]